name: llamagen
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.0
      - accelerate==1.8.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - args==0.1.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - bitsandbytes==0.46.0
      - braceexpand==0.1.7
      - bs4==0.0.2
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - clint==0.5.1
      - clip==0.2.0
      - clip-score==0.2.1
      - datasets==3.6.0
      - diffusers==0.34.0
      - dill==0.3.8
      - distro==1.9.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fairscale==0.4.13
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - grpcio==1.73.1
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.5
      - hpsv2==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - idna==3.10
      - image-reward==1.5
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - json-repair==0.47.3
      - jsonlines==4.0.0
      - markdown==3.8.2
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.5.1
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - openai==1.92.2
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.0
      - pillow==11.2.1
      - pluggy==1.6.0
      - propcache==0.3.2
      - protobuf==3.20.3
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pytest==7.2.0
      - pytest-split==0.8.0
      - python-dateutil==2.9.0.post0
      - pytorch-fid==0.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tiktoken==0.9.0
      - timm==1.0.19
      - tokenizer==3.4.5
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.53.0
      - triton==3.3.1
      - trl==0.19.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - webdataset==1.0.2
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: llamagen
